### ISSUE TITLE
problem with multirobot branch

### ISSUE THREAD

**Issue by omershalev** [jackal/jackal#40]
Hi,
I'm trying to spawn two jackals in Gazebo and I'm working with the multirobot branches of all the relevant repositories.
The simulation is launched successfully and I can even send cmd_vel commands to the different robot but there is a problem with the IMUs: on both IMU topics I see the same values.
After some debug, I think that the problem stems from the jackal.gazebo file (under the jackal_description package): the entry <bodyName>imu_link</bodyName> is causing the failure.
If I change it to <bodyName>$(arg robot_name)::base_link</bodyName> then I see that the two IMU reads are different.
1. Can somebody confirm the problem that I'm seeing?
2. I don't know if $(arg robot_name)::base_link is the correct bodeName (when trying $(arg robot_name)::imu_link, Gazebo complains that there is no such body)

Thanks.

**Comment by civerachb-cpr** [comment]
Closing this as it's related to a _very_ old branch that isn't maintained anymore it seems.

We're planning on improving our multi-robot support soon, though those changes will likely be in the jackal_simulation repository instead of here.

If this is still a priority problem, please open a new issue.
