### ISSUE TITLE
Issues with the networking 

### ISSUE THREAD

**Issue by utsavpatel22** [jackal/jackal#76]
Hi, 
We bought Clearpath Jackal a year back. We had reinstalled the OS on the system due to some issues we faced with the ROS packages. After reinstalling the OS, we are facing issues with the networking. The Ethernet IP is not stable, so many times the default Ethernet IP (192.168.131.1) doesn't work. I tried to directly connect to the non static Ethernet IP but that always doesn't work. I am copying the /etc/network/interfaces file here, 

auto lo br0 br0:0
iface lo inet loopback

#### Bridge together physical ports on machine, assign standard Clearpath Robot IP.
iface br0 inet static
  bridge_ports regex (eth.*)|(en.*)
  address 192.168.131.1
  netmask 255.255.255.0
  bridge_maxwait 0

auto wlan0
iface wlan0 inet dhcp
                wpa-ssid NETGEAR21-5G
                wpa-psk **************

#### maintenance, ethernet radio support, etc.
iface br0:0 inet dhcp

**Comment by civerachb-cpr** [comment]
Can you run `wicd-curses` and open the preferences by pressing shift + P.  The "Wired Interface" section should be blank.  If there's something in it (e.g. "br0" or "en0s2") delete it, save your preferences, and reboot the robot.  Sometimes wicd tries managing the wired interface, even though it's configured through network/interfaces.

Similarly, if you're manually configuring the wireless network through the interfaces file, you may want to disable managing the wireless through wicd too.

**Comment by utsavpatel22** [comment]
Thanks @civerachb-cpr for responding. I removed "en0s2" from the "Wired Interface" and rebooted the machine, still I cant connect to the static IP 192.168.131.1.

**Comment by civerachb-cpr** [comment]
When you say "cannot connect" how are you trying to connect?  Is the robot connected to a router or a switch? Or do you have an ethernet cable connected directly from your computer to the second ethernet port on the robot?

**Comment by utsavpatel22** [comment]
I have the Ethernet cable directly from the robot (Static Port) to the PC.

**Comment by civerachb-cpr** [comment]
Because of the bridged network it doesn't matter which port you connect to: either one can be used to access the static network inside the robot.

How have you configured your PC's ethernet port?  Because the robot does not have a DHCP server running on it you cannot just plug the cable into your PC; you need to configure your PC's wired network to use a static IP address with the following parameters:

```
address: 192.168.131.200   # technically anything on the 192.168.131.* subnet will work, but some addresses <=100 are reserved for sensors, MCU hardware, etc... -- see below
netmask: 255.255.255.0
```

You can omit setting the gateway, as this isn't configuring an internet-facing network connection.

______________
Additional information regarding reserved IP addresses:

The only truly reserved IP addresses on the 192.168.131.* subnet are 192.168.131.1 for the robot's main PC and 192.168.131.2 for the MCU.  By default clearpath uses the following other addresses, though they can be configured if necessary:

* 192.168.131.1 -- Robot's main PC
* 192.168.131.2 -- Robot's MCU
* 192.168.131.3-4 -- Unassigned at present
* 192.168.131.5-9 -- Robot's secondary, tertiary, etc... PCs (e.g. main PC + Jetson for image processing in the same robot)
* 192.168.131.10-19 -- RGB cameras (e.g. pan-tilt cameras, Axis multi-camera controllers).  Additional cameras will be .11 to .19
* 192.168.131.20-29 -- Lidar.  If there are front & rear lidars the front one is .20, and the rear one is .21
* 192.168.131.30-34 -- GPS
* 192.168.131.35-39 -- Sonar (rarely used, but sometimes)
* 192.168.131.40-44 -- Arms. .40 is primary/left and .41 is secondary/right.  Additional arms as needed
* 192.168.131.45-49 -- Grippers/other manipulators.  Should be ordered the same as the arms
* 192.168.131.50 -- remote base station
* 192.168.131.51-69 -- Radios (e.g. Microhard)
* 192.168.131.79-99 -- Unassigned at present
* 192.168.131.100-254 -- DHCP & external diagnostic PCs

**Comment by utsavpatel22** [comment]
Thanks, @civerachb-cpr for the detailed answer. On my laptop, I have set up the static IP according to the instructions given in the Jackal's manual. The static IP is set to 192.168.131.51. The main issue is that the connection is very unstable, sometimes I can ssh to Jackal using the IP 192.168.131.1 and other times I can't connect. If I run "ifconfig" on Jackal (By connecting a screen directly to Jackal) I don't see "br0" listed.

**Comment by civerachb-cpr** [comment]
Did you install the Jackal software using the Clearpath ISOs (https://packages.clearpathrobotics.com/stable/images/latest/), or did you use a standard Ubuntu image?

**Comment by utsavpatel22** [comment]
I am using the Clearpath ISO. Is it possible that I can just get the network configuration files?

**Comment by civerachb-cpr** [comment]
Can you please confirm that the bridge-utils package is installed on the robot?

**Comment by utsavpatel22** [comment]
Yes, it is installed.

**Comment by utsavpatel22** [comment]
I was going through some articles, br0 bridge was disabled. I enabled it, it is bridging the right ports but "ifconfig" doesnt show the static IP 192.168.131.1 for br0.

**Comment by civerachb-cpr** [comment]
Can you run `sudo ifup br0`?  It may be that the interface just isn't coming up for whatever reason.  Worst-case you can work-around the problem by forcing the interface to come up by putting `ifup br0` in `/etc/rc.local`

**Comment by utsavpatel22** [comment]
I ran `sudo ifconfig br0 up` and it worked. But after it is up, I can see it in the list provided by `ifconfig` but it doesnt have an IP address, it is in UP state though. Whenever the system ran I could see the IP 192.168.131.1 under `br0`. I have attached a screenshot. 
![ifconfig](https://user-images.githubusercontent.com/36716888/102276665-1f6bcc00-3ef5-11eb-8fc9-677867a72420.png)

**Comment by civerachb-cpr** [comment]
Is this screenshot taken from directly on the robot, or are you SSH'd in from an Ubuntu desktop installation?

It looks like you have some other process (possibly network-manager?) taking control of your wired interfaces.  `enp3s0` should not have its own IP address; that should be connected through the bridge via br0:0.

If you've installed a full desktop on your robot it's possible that you now have competing network-management tools that are clobbering each other.

**Comment by utsavpatel22** [comment]
This screenshot is taken from my laptop that is connected to the robot using a direct Ethernet connection. I am using `enp3s0` interface that has the IP `169.254.81.20`

**Comment by civerachb-cpr** [comment]
If your laptop is connected to the robot directly your laptop should have a statically-configured IP address on the 192.168.131.* address space.  If your robot and laptop are both connected to a router then you can use whatever DHCP address the router assigned, and log into the robot using the robot's assigned DHCP address.

**Comment by utsavpatel22** [comment]
I have configured a static IP on my laptop, but when I connect the laptop to the robot, it doesn't show the robot's IP which is supposed to be `192.168.131.1` and I SSH into the robot using the IP.

**Comment by civerachb-cpr** [comment]
When you say "it doesn't show the robot's IP" what is "it" in this context?

**Comment by utsavpatel22** [comment]
When I connect the robot to the laptop after setting up the static IP on the laptop, the laptop doesn't show the IP of the robot that is supposed to be `192.168.131.1`. And if I try to SSH from my laptop to the robot (on IP `192.168.131.1`) the laptop doesnt connect to the robot. On the robot, if I run `ifconfig`, that also doesnt show the bridge IP `192.168.131.1` under `br0`.

**Comment by civerachb-cpr** [comment]
On the robot, can you please run 

```
sudo ifdown br0
sudo ifup br0
```

and then run

```
ifconfig br0
```

**Comment by utsavpatel22** [comment]
@civerachb-cpr thank you, it worked. Should I just put `ifup br0` in `/etc/rc.local`?

**Comment by civerachb-cpr** [comment]
Yes, you can do that.  In an ideal world you wouldn't need to do that, but forcing the network to come up with rc.local is fine if it gets around the problem and lets you get back to working with your robot.

**Comment by utsavpatel22** [comment]
Thank you, @civerachb-cpr It works. Closing the issue.
